### ISSUE TITLE
usage example

### ISSUE THREAD

**Issue by ilanah** [JoshDellay/jquery-mobile-menu#1]
hi -
can you please add usage example for this package in meteor ?

**Comment by JoshDellay** [comment]
Sure, I can try to do that for you. Ill reply when completed.

**Comment by JoshDellay** [comment]
Ilanah, sorry for the late response... I have added an example to the mobile menu repository for meteor.

**Comment by rubenlpz** [comment]
Meteor repository is offline now =(
